### ISSUE TITLE
Gradle dependency no longer recognizes kottle

### ISSUE THREAD

**Issue by AlexCouch** [autaut03/kottle#10]
I am just wondering if you changed the way you use kottle as a dependency. Your readme hasn't been updated since 1.0.6 so did you get a maven or something?

**Comment by autaut03** [comment]
Hey. No, I did not change anything, though readme is a bit outdated.

**Comment by EllieP97** [comment]
Hi!, having the same issue as above, 
When compiling I get 
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find kottle:Kottle:1.1.1.
(I am using 1.1.1 as on Curse it shows as the compatible version with 1.14, however I also tried other versions with the same result)

**Comment by autaut03** [comment]
@Trxnce Hi. I'll look into it later today.

**Comment by EllieP97** [comment]
Hi, any updates on this?

**Comment by autaut03** [comment]
@AlexCouch, @Trxnce,

So I just tried it with [this](https://gist.github.com/autaut03/a4b7226d1a6e974bc16e8cdb0f1f8567) gradle config and it worked perfectly.

Could you show me your config you're having problems with?

**Comment by EllieP97** [comment]
Hi, using the gradle config you posted seems to of fixed the issue and Minecraft now compiles and launches, appreciate the help

**Comment by Trxnce** [comment]
Ok, just started from a fresh Forge install and this issue still occurs, so I believe it might be to do with Kottle

**Comment by autaut03** [comment]
@Trxnce Please, provide your gradle config so I can reproduce it. Thanks in advance.

**Comment by EllieP97** [comment]
Hi, sorry mate but I deleted the old file when I got the new one working, one thing I noted I was missing from the one you posted was 

repositories {
    maven { url 'https://minecraft.curseforge.com/api/maven/' }
    mavenCentral()
}

Once I added that it seems to work, the gradle config I used before was extremely similar to the one on the readme, just with the group and archive name specified

**Comment by autaut03** [comment]
@Trxnce No problem.
@AlexCouch Has this resolved your issue too?

**Comment by AlexCouch** [comment]
Yes, it was just a simple maven script issue thank you.
