### ISSUE TITLE
Provide slim jar without packaged kotlin library

### ISSUE THREAD

**Issue by mattmess1221** [autaut03/kottle#21]
During dev-time, viewing kotlin sources in intellij often selects the class from Kottle's jar instead of the proper kotlin-jvm dependency. Since sources are not available when grabbing from curse, intellij can't find the sources for kotlin and shows decompiled data instead. This is less than ideal as it removes javadocs as well.

With kottle
![image](https://user-images.githubusercontent.com/3409962/71757541-cbdbac00-2e64-11ea-865b-676253d0dfb1.png)

Without kottle
![image](https://user-images.githubusercontent.com/3409962/71757581-0cd3c080-2e65-11ea-8bf2-6f5e77c02a8a.png)

Providing a slim jar without kotlin for the development environment would resolve this issue.

**Comment by autaut03** [comment]
Hey. By any chance, might clicking "Choose sources" also fix the problem?

**Comment by mattmess1221** [comment]
Yes, but it can become tedious to attach each sources jar. If you give the jar task a classifier (shadowJar overwrites it), I could at least import it using jitpack.

**Comment by autaut03** [comment]
Haven't had much time to look into this, sorry.

If this is still relevant for you, take a look at https://github.com/autaut03/kottle/pull/22.
