### ISSUE TITLE
[question] Will this support 1.15.2 in the future, and how long until it does?

### ISSUE THREAD

**Issue by CmdrNorthpaw** [autaut03/kottle#23]

**Comment by autaut03** [comment]
Hey @CmdrNorthpaw.

Yes, I'm working on it. I will leave the issue open for others to see.

**Comment by CmdrNorthpaw** [comment]
I see in commit 4fe398f that you've committed a 1.15 update, but you haven't updated Curse yet. Is the 1.15 update done or no?

**Comment by oprypkhantc** [comment]
It is, yes. Sorry for the delay. I'll publish it today.

**Comment by autaut03** [comment]
Published [1.5.0](https://www.curseforge.com/minecraft/mc-mods/kottle/files/2895068).
