### ISSUE TITLE
Classloading errors

### ISSUE THREAD

**Issue by Bluexin** [autaut03/kottle#3]
We have noticed some class loading errors caused by the wrong class loader being used.
Just posting the issue here for the record, I'll look into this myself in the evening (with a simple reproducer), and either provide a PR or more details for reproducing the error if I don't have the time to fix it myself.

**Comment by autaut03** [comment]
Hey. Sure, I'll be happy to look into it. However, just to potentially save you time, I will have to warn you that if you get `java.lang.ClassCastException: net.alexwells.kottle.FMLKotlinModContainer cannot be cast to net.minecraftforge.fml.ModContainer` then it's a problem on your side, and you have to drop the mod jar into respective folder, even in dev env.

Otherwise, ignore this.

**Comment by Bluexin** [comment]
No, it's an issue with actual class loading (as the same class loaded by two different class loaders gives two non identical classes for obvious reasons).

**Comment by autaut03** [comment]
Hey. Any updates on this?

**Comment by Bluexin** [comment]
Sorry, I got caught up in other stuff and forgot about this.

**Comment by MairwunNx** [comment]
@autaut03 I am updating the discussion. I got `java.lang.ClassCastException: net.alexwells.kottle.FMLKotlinModContainer cannot be cast to net.minecraftforge.fml.ModContainer`, it would be interesting to know how to fix this, I run the client through runners (gradle tasks).

**Comment by autaut03** [comment]
> @autaut03 I am updating the discussion. I got `java.lang.ClassCastException: net.alexwells.kottle.FMLKotlinModContainer cannot be cast to net.minecraftforge.fml.ModContainer`, it would be interesting to know how to fix this, I run the client through runners (gradle tasks).

Hey. Have you put the gradle.config from readme into your gradle.config? After running the client once, is there a Kottle-1.1.1.jar in mods folder?

**Comment by MairwunNx** [comment]
A couple of minutes ago I fixed it after reading readme. 
**Issue resolved by adding tasks installMods.**
