### ISSUE TITLE
NoSuchMethodError when grabbing annotations

### ISSUE THREAD

**Issue by ejektaflex** [autaut03/kottle#4]
It seems that `net.minecraftforge.forgespi.language.ModFileScanData.getAnnotations()` cannot be found. Using:

Forge 25.0.63
Kotlin 1.3.21
Kottle 1.0.5

It seems that between `forgespi` v0.6.0 to v0.10.0 this method now returns a `Set<AnnotationData>` instead of a `List<AnnotationData`, which may be the cause of the error (It cannot find a method with the matching JVM signature, since the return type has changed)

build.gradle:
https://gist.github.com/ejektaflex/ee929bfceecc131d704422d61ae4d13c

Log:
https://gist.github.com/ejektaflex/4b64858f227cc2b4c8f9d3b7103f1f9d

It would be easier to talk to you on Discord, if you have one you can message me at Ejektaflex#4616 :)

**Comment by ejektaflex** [comment]
Pull request added in #5 fixing said issue!

**Comment by autaut03** [comment]
Merged #5 and released 1.0.6.

Offtop PS: I couldn't contact you on Discord, because you have friend requests disabled, but you can contact me instead, I now have the info in my profile.
