### ISSUE TITLE
The mod file <...> has mods that were not found on 1.14

### ISSUE THREAD

**Issue by natanfudge** [autaut03/kottle#7]
I get this error when trying to run on 1.14. 
Crash log: https://hastebin.com/ubihoyawof.sql

**Comment by thedarkcolour** [comment]
Well...? How did you fix it!?

**Comment by natanfudge** [comment]
I switched to fabric.

**Comment by thedarkcolour** [comment]
Thanks

**Comment by natanfudge** [comment]
That might have not been the answer you were looking for, but it’s a true story.

**Comment by autaut03** [comment]
For anyone wondering: this was caused by Kottle missing in `mods/` folder.
